### ISSUE TITLE
XmlParser#domToXml does not encode XML entities

### ISSUE THREAD

**Issue by Geolykt** [codemonstur/simplexml#9]
In my case `&amp;` would be (correctly) read as `&`, however when it came to writing the XML back to disk, the library would write it as `&`, which I deem incorrect or at the very least unexpected behaviour.

Wrapping https://github.com/codemonstur/simplexml/blob/70652a1c70897fa3aa4a1398aa710f8c385734aa/src/main/java/xmlparser/XmlWriter.java#L63 in a `escapeXml(text, shouldEncodeUTF8())` seems to resolve this issue, as done in https://github.com/codemonstur/simplexml/blob/70652a1c70897fa3aa4a1398aa710f8c385734aa/src/main/java/xmlparser/XmlWriter.java#L76 however I am not entirely sure of the full consequences of this action, so in the end that is up to you to estimate. Regardless, it would be great to have some way of escaping HTML/XML entities when the library supports unescaping them already.

**Comment by codemonstur** [comment]
What the everloving &$^%. You are being very kind calling it unexpected behavior. It generates invalid XML which in best case scenario results in a parsing error, but could also turn into a security vulnerability in certain circumstances. And there was supposed to be a unit test that covered this. Humbling experience :(. 

Anyway, I've fixed the issue and pushed 2 new versions to Maven Central. 3.1.2 and 2.10.1. They should be available soon. I've added unit tests to cover your case and also for serializing Maps. That code wasn't broken but needed to be covered. Can you check?

Separately there is the issue of escaping HTML entities. At the moment only unescaping HTML entities is supported because, well, I needed that one time. Shouldn't be too hard to add I think, will get to that as soon as I can.

**Comment by Geolykt** [comment]
Thanks for the quick fix. And quickly testing the scenario that made me initially uncover this issue seems like the fix is working. And yeah, I was quite confused about the unit test scenario which is why I was a bit reluctant with filing the bug report at first (especially considering that my usual experience with these kind of things is WAI)
